version: '3.8'
services:
  internetbanking:
    image: aryandockerhub/ib-image:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
    volumes:
      - /var/lib/ib-image
  mobilebanking:
    image: aryandockerhub/mb-image:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
    volumes:
      - /var/lib/mb-image
  insurance:
    image: aryandockerhub/insurance:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
    volumes:
      - /var/lib/insurance
  loan:
    image: aryandockerhub/loans:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
    volumes:
      - /var/lib/loans
